import { z } from "zod";

export const blogArticleSchema = z.object({
  slug: z.string().min(1).max(200),
  imageUrl: z.string().max(2000).optional().default(""),
  imageAltEn: z.string().max(500).optional().nullable(),
  imageAltAr: z.string().max(500).optional().nullable(),
  category: z.string().max(100).optional().nullable(),
  tags: z.string().max(500).optional().nullable(),
  day: z.string().max(10).optional().default(""),
  monthEn: z.string().max(50).optional().default(""),
  monthAr: z.string().max(50).optional().default(""),
  readTimeEn: z.string().max(50).optional().default(""),
  readTimeAr: z.string().max(50).optional().default(""),
  titleEn: z.string().max(500).optional().default(""),
  titleAr: z.string().max(500).optional().default(""),
  excerptEn: z.string().max(2000).optional().default(""),
  excerptAr: z.string().max(2000).optional().default(""),
  bodyEn: z.string().max(500_000).optional().default(""),
  bodyAr: z.string().max(500_000).optional().default(""),
  suggestedBreakAfter: z.number().int().positive().optional().nullable(),
  published: z.boolean().optional().default(true),
  sortOrder: z.number().int().min(0).max(100_000).optional().default(0),
  metaTitleEn: z.string().max(200).optional().nullable(),
  metaTitleAr: z.string().max(200).optional().nullable(),
  metaDescriptionEn: z.string().max(500).optional().nullable(),
  metaDescriptionAr: z.string().max(500).optional().nullable(),
  ogImageUrl: z.string().max(2000).optional().nullable(),
  keywords: z.string().max(1000).optional().nullable(),
});
